"""empty message

Revision ID: 55c3f3c19b0d
Revises: 2badcdcdf527
Create Date: 2026-04-01 17:27:02.557452-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c3f3c19b0d'
down_revision: Union[str, Sequence[str], None] = '2badcdcdf527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_stats', 'raw_data_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_stats', 'raw_data_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
