"""empty message

Revision ID: 45d98acea579
Revises: 55c3f3c19b0d
Create Date: 2026-04-10 12:43:38.722312-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d98acea579'
down_revision: Union[str, Sequence[str], None] = '55c3f3c19b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum('FEMALE', 'MALE', name='genderenum')
    dep_enum = sa.Enum('AMAZONAS', 'ANCASH', 'APURIMAC', 'AREQUIPA', 'AYACUCHO', 'CAJAMARCA', 'CALLAO', 'CUSCO', 'HUANCAVELICA', 'HUANUCO', 'ICA', 'JUNIN', 'LA_LIBERTAD', 'LAMBAYEQUE', 'LIMA', 'LORETO', 'MADRE_DE_DIOS', 'MOQUEGUA', 'PASCO', 'PIURA', 'PUNO', 'SAN_MARTIN', 'TACNA', 'TUMBES', 'UCAYALI', name='perudepartmentenum')
    gender_enum.create(op.get_bind(), checkfirst=True)
    dep_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('videos', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('videos', sa.Column('department', dep_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'department')
    op.drop_column('videos', 'gender')
    # ### end Alembic commands ###
    sa.Enum(name='genderenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='perudepartmentenum').drop(op.get_bind(), checkfirst=True)
