"""empty message

Revision ID: 2badcdcdf527
Revises: 0bf6b24d331d
Create Date: 2026-03-31 17:12:47.409731-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2badcdcdf527'
down_revision: Union[str, Sequence[str], None] = '0bf6b24d331d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videos', ['url'])
    op.create_foreign_key(None, 'videos', 'video_stats', ['last_stat_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='unique')
    # ### end Alembic commands ###
